version: "3.8"

services:
  tracing:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
      - 14268:14268
      - 4318:4318

  postgres-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      DATABASE_COUNT: 5
      DATABASE_NAMES: auth,user,prestation,report,review
    volumes:
      - postgres-db:/var/lib/postgresql/data

  mongo-db:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=payment
      - MONGO_INITDB_DATABASE=order
      - MONGO_INITDB_DATABASE=deliverable
      - MONGO_INITDB_DATABASE=review
      - MONGO_INITDB_DATABASE=favorite
    ports:
      - "27017:27017"
    volumes:
      - "mongo-db:/data/db"

  gateway-service:
    build:
      context: ./gateway-service
      target: dev
    command: npm run start:dev
    volumes:
      - ./gateway-service:/home/node
      - /home/node/node_modules
    environment:
      NODE_OPTIONS: --max-old-space-size=16192
      PORT: 3000
      TRACER_ENDPOINT: http://tracing:4318/v1/traces
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - user-service
      - prestation-service
      - review-service
      - report-service
      - payment-service

  auth-service:
    build:
      context: ./auth-service
      target: dev
    command: npm run start:dev
    volumes:
      - ./auth-service:/home/node
      - /home/node/node_modules
    environment:
      NODE_OPTIONS: --max-old-space-size=16192
      PORT: 3001
      TRACER_ENDPOINT: http://tracing:4318/v1/traces
    ports:
      - "5555:5555"

  user-service:
    build:
      context: ./user-service
      target: dev
    command: npm run start:dev
    volumes:
      - ./user-service:/home/node
      - /home/node/node_modules
    environment:
      NODE_OPTIONS: --max-old-space-size=16192
      PORT: 3002
      TRACER_ENDPOINT: http://tracing:4318/v1/traces
      DATABASE_URL: mongodb://root:password@mongo-db:27017/user?authSource=admin&directConnection=true
    ports:
      - "5556:5555"
    depends_on:
      - postgres-db

  prestation-service:
    build:
      context: ./prestation-service
      target: dev
    command: npm run start:dev
    volumes:
      - ./prestation-service:/home/node
      - /home/node/node_modules
    environment:
      PORT: 3003
      TRACER_ENDPOINT: http://tracing:4318/v1/traces
      DATABASE_URL: mongodb://root:password@mongo-db:27017/prestation?authSource=admin&directConnection=true
    ports:
      - "5557:5555"
    depends_on:
      - postgres-db

  review-service:
    build:
      context: ./review-service
      target: dev
    command: npm run start:dev
    volumes:
      - ./review-service:/home/node
      - /home/node/node_modules
    environment:
      PORT: 3004
      TRACER_ENDPOINT: http://tracing:4318/v1/traces
      DATABASE_URL: mongodb://root:password@mongo-db:27017/review?authSource=admin&directConnection=true
    ports:
      - "5558:5555"
    depends_on:
      - postgres-db

  report-service:
    build:
      context: ./report-service
      target: dev
    command: npm run start:dev
    volumes:
      - ./report-service:/home/node
      - /home/node/node_modules
    environment:
      PORT: 3005
      TRACER_ENDPOINT: http://tracing:4318/v1/traces
      DATABASE_URL: postgresql://postgres:postgres@postgres-db:5432/report
    ports:
      - "5559:5555"
    depends_on:
      - postgres-db

  payment-service:
    build:
      context: ./payment-service
      target: dev
    command: npm run start:dev
    volumes:
      - ./payment-service:/home/node
      - /home/node/node_modules
    environment:
      PORT: 3006
      TRACER_ENDPOINT: http://tracing:4318/v1/traces
      DATABASE_URL: mongodb://root:password@mongo-db:27017/payment?authSource=admin&directConnection=true
    # ports:
    #     - "5560:5555"
    depends_on:
      - postgres-db

volumes:
  postgres-db:
  mongo-db:
