version: "3.8"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./auth-service
      target: dev
    command: npm run start:dev
    volumes:
      - ./auth-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - db

  gateway-service:
    build:
      context: ./gateway-service
      target: dev
    command: npm run start:dev
    volumes:
      - ./gateway-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - db
  
  user-service:
    build:
      context: ./user-service
      target: dev
    command: npm run start:dev
    volumes:
      - ./user-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - db
      

volumes:
  db_data:
