apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cinqoo

resources:
    - ../../base

namePrefix: staging-

commonLabels:
    env: staging

configMapGenerator:
    - name: variables
      env: .env
      options:
          disableNameSuffixHash: true
secretGenerator:
    - name: secrets
      env: .env.secrets
      options:
          disableNameSuffixHash: true
patches:
    - patch: |-
          - op: replace
            path: /spec/type
            value:
              LoadBalancer
      target:
          kind: Service
          name: gateway-service
