apiVersion: apps/v1
kind: Deployment
metadata:
    name: gateway-service
    namespace: cinqoo
    labels:
        app: gateway-service
spec:
    selector:
        matchLabels:
            app: gateway-service
    template:
        metadata:
            labels:
                app: gateway-service
        spec:
            containers:
                - name: gateway-service
                  image: europe-west9-docker.pkg.dev/cinqoo/challenge/gateway-service:latest
                  imagePullPolicy: Always
                  env:
                      - name: PORT
                        value: "3000"
                  ports:
                      - containerPort: 3000
                  resources:
                      limits:
                          cpu: 500m
                      requests:
                          cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
    name: gateway-service
    namespace: cinqoo
    labels:
        app: gateway-service
spec:
    type: NodePort
    selector:
        app: gateway-service
    ports:
        - name: default
          port: 3000
          targetPort: 3000
        - name: my-https-port
          port: 443
          targetPort: 3000
        - name: my-http-port
          port: 80
          targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: gateway-service
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: gateway-service
    minReplicas: 1
    maxReplicas: 10
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 60
