apiVersion: apps/v1
kind: Deployment
metadata:
    name: report-service
    namespace: cinqoo
    labels:
        app: report-service
spec:
    selector:
        matchLabels:
            app: report-service
    template:
        metadata:
            labels:
                app: report-service
        spec:
            containers:
                - name: report-service
                  image: europe-west9-docker.pkg.dev/cinqoo/challenge/report-service:latest
                  imagePullPolicy: Always
                  env:
                      - name: PORT
                        value: "3000"
                      - name: DATABASE_URL
                        valueFrom:
                            secretKeyRef:
                                name: secrets
                                key: REPORT_DATABASE_URL
                  ports:
                      - containerPort: 3000
                  resources:
                      limits:
                          cpu: 500m
                      requests:
                          cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
    name: report-service
    namespace: cinqoo
    labels:
        app: report-service
spec:
    type: ClusterIP
    selector:
        app: report-service
    ports:
        - port: 3000
          targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: report-service
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: report-service
    minReplicas: 1
    maxReplicas: 2
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 60
