
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: secrets
        key: DATABASE_URL

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: TRACER_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: secrets
        key: TRACER_ENDPOINT

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: secrets
        key: JWT_SECRET
