apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cinqoo

resources:
  - ../../base

configMapGenerator:
  - name: variables
    files: 
      - .env
    options:
      disableNameSuffixHash: true
secretGenerator:
  - name: secrets
    envs:
      - .env.secrets
    options:
      disableNameSuffixHash: true
