apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cinqoo

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  env: dev

configMapGenerator:
  - name: variables
    env: .env
    options:
      disableNameSuffixHash: true
secretGenerator:
  - name: secrets
    env: .env.secrets
    options:
      disableNameSuffixHash: true

patches:
  - target:
      kind: HorizontalPodAutoscaler
    patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 2
      - op: replace
        path: /spec/metrics/0/resource/target/averageUtilization
        value: 80
