export enum RECEIVED_EVENTS {
  'START_QUIZ' = 'START_QUIZ',
  'ANSWER_QUESTION' = 'ANSWER_QUESTION',
}

export enum SENT_EVENTS {
  'ERROR' = 'ERROR',
  'WARNING' = 'WARNING',
  'NEW_QUESTION' = 'NEW_QUESTION',
  'QUIZ_OVER' = 'QUIZ_OVER',
}
