apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cinqoo

resources:
    - _namespace.yaml
    - pvc.yaml
    - ../../base
    - ingress.yaml
    - cert.yaml
    - backend.yaml

configMapGenerator:
    - name: variables
      env: .env
      options:
          disableNameSuffixHash: true
secretGenerator:
    - name: secrets
      env: .env.secrets
      options:
          disableNameSuffixHash: true
patches:
    - patch: |-
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
              name: TRACK_ERRORS
              value: true
      target:
          kind: Deployment
          name: gateway-service
    - patch: |-
          - op: add
            path: /metadata/annotations
            value:
              cloud.google.com/neg: '{"ingress": true}'
      target:
          kind: Service
          name: gateway-service
    - patch: |-
          - op: add
            path: /metadata/annotations
            value:
              cloud.google.com/app-protocols: '{"my-https-port":"HTTPS","my-http-port":"HTTP"}'
      target:
          kind: Service
          name: gateway-service
    - patch: |-
          - op: add
            path: /metadata/annotations
            value:
              cloud.google.com/neg: '{"ingress": true}'
      target:
          kind: Service
          name: hybrid-service
    - patch: |-
          - op: add
            path: /metadata/annotations
            value:
              cloud.google.com/app-protocols: '{"my-https-port":"HTTPS","my-http-port":"HTTP"}'
      target:
          kind: Service
          name: hybrid-service
    - patch: |-
          - op: add
            path: /metadata/annotations
            value:
              cloud.google.com/backend-config: '{"ports": {
                "3000": "statefull-backendconfig",
                "3001": "statefull-backendconfig",
                "443": "statefull-backendconfig",
                "80": "statefull-backendconfig",
                "default": "statefull-backendconfig",
                "my-ms-port": "statefull-backendconfig",
                "my-https-port": "statefull-backendconfig",
                "my-http-port": "statefull-backendconfig"
              }}'
      target:
          kind: Service
          name: hybrid-service
    - patch: |-
          - op: add
            path: /metadata/annotations
            value:
              cloud.google.com/neg: '{"ingress": true}'
      target:
          kind: Service
          name: quiz-service
    - patch: |-
          - op: add
            path: /metadata/annotations
            value:
              cloud.google.com/app-protocols: '{"my-https-port":"HTTPS","my-http-port":"HTTP"}'
      target:
          kind: Service
          name: quiz-service
    - patch: |-
          - op: add
            path: /metadata/annotations
            value:
              cloud.google.com/backend-config: '{"ports": {
                "3000": "statefull-backendconfig",
                "3002": "statefull-backendconfig",
                "443": "statefull-backendconfig",
                "80": "statefull-backendconfig",
                "default": "statefull-backendconfig",
                "my-ms-port": "statefull-backendconfig",
                "my-https-port": "statefull-backendconfig",
                "my-http-port": "statefull-backendconfig"
              }}'
      target:
          kind: Service
          name: quiz-service
    - path: gateway-service-patch.yaml
      target:
          kind: Deployment
          name: gateway-service
