apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cinqoo

resources:
  - ../../base
  - ingress.yaml

configMapGenerator:
  - name: variables
    env: .env
    options:
      disableNameSuffixHash: true
secretGenerator:
  - name: secrets
    env: .env.secrets
    options:
      disableNameSuffixHash: true
patches:
  - patch: |-
      - op: add
        path: /metadata/annotations
        value:
          cloud.google.com/neg: '{"ingress": true}'
    target:
      kind: Service
      name: gateway-service
