apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cinqoo

resources:
  - ../../base
  
configMapGenerator:
  - name: variables
    env: .env
    options:
      disableNameSuffixHash: true
secretGenerator:
  - name: secrets
    env: .env.secrets
    options:
      disableNameSuffixHash: true