apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: gateway-storage
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
    tier: standard
    network: default
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: gateway-storage
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: gateway-storage
    resources:
        requests:
            storage: 10Gi
