name: Deliverable Test

on:
    workflow_dispatch:
    pull_request:
        branches:
            - master
        paths:
            - deliverable-service/**
        types:
            - opened
            - synchronize

jobs:
    test_deliverable:
        name: Test Deliverable service before merging
        runs-on: ubuntu-latest
        steps:
            - name: Test Deliverable service
              uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm test
