name: front build and push docker image

on:
    workflow_dispatch:
    push:
        branches:
            - master
        paths:
            - front/**

jobs:
    push-to-gcr:
        permissions:
            contents: "read"
            id-token: "write"
        name: Build and push image to GCR
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: get-npm-version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@v1.3.1
              with:
                  path: front
            - id: auth
              name: Authenticate with Google Cloud
              uses: google-github-actions/auth@v0
              with:
                  token_format: access_token
                  workload_identity_provider: ${{ secrets.PROVIDER_ID}}
                  service_account: ${{ secrets.SERVICE_ACCOUNT}}
                  access_token_lifetime: 300s
            - name: Login to Artifact Registry
              uses: docker/login-action@v1
              with:
                  registry: europe-west9-docker.pkg.dev
                  username: oauth2accesstoken
                  password: ${{ steps.auth.outputs.access_token }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: "{{defaultContext}}:front"
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: |
                      europe-west9-docker.pkg.dev/${{ secrets.PROJECT_ID }}/challenge/front:latest
                      europe-west9-docker.pkg.dev/${{ secrets.PROJECT_ID }}/challenge/front:${{ steps.package-version.outputs.current-version}}
