name: API-gateway build and push docker image

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - master
    paths:
      - gateway-service/**

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - id: auth
      #   name: Authenticate with Google Cloud
      #   uses: google-github-actions/auth@v0
      #   with:
      #     token_format: access_token
      #     workload_identity_provider: ${{ secrets.PROVIDER_ID}}
      #     service_account: ${{ secrets.SERVICE_ACCOUNT}}@${{ secrets.PROJECT_ID}}.iam.gserviceaccount.com
      #     access_token_lifetime: 300s
      - name: echo
        run: echo ${{ secrets.PROVIDER_ID}} ${{ secrets.SERVICE_ACCOUNT}}@${{ secrets.PROJECT_ID}}.iam.gserviceaccount.com
