name: Push k8s infra

on:
    workflow_dispatch:

jobs:
    push:
        permissions:
            contents: "read"
            id-token: "write"
        name: push
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: "Authenticate with GCP"
              uses: google-github-actions/auth@v1
              with:
                  workload_identity_provider: ${{ secrets.PROVIDER_ID}}
                  service_account: ${{ secrets.SERVICE_ACCOUNT}}

            - name: "Set up Cloud SDK"
              uses: "google-github-actions/setup-gcloud@v1"
              with:
                  version: ">= 363.0.0"

            - run: gcloud --quiet auth configure-docker

            - id: "get-credentials"
              uses: "google-github-actions/get-gke-credentials@v1"
              with:
                  cluster_name: ${{ secrets.GKE_CLUSTER_NAME}}
                  location: ${{ secrets.GKE_CLUSTER_LOCATION}}

            - name: Set up Kustomize
              run: |-
                  curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
                  chmod u+x ./kustomize

            - name: Set up secret
              working-directory: ./infra/k8s/overlays/prod
              run: |-
                  cp .env.example .env
                  cp .env.secrets.example .env.secrets
                  sed -i 's/<user>/${{ secrets.MONGODB_USER }}/g' .env.secrets
                  sed -i 's/<password>/${{ secrets.MONGODB_PASSWORD }}/g' .env.secrets
                  sed -i 's/<mongouri>/${{ secrets.MONGODB_URI }}/g' .env.secrets
                  sed -i 's/<jwtsecret>/${{ secrets.JWT_SECRET }}/g' .env.secrets
                  sed -i 's/<stsk>/${{ secrets.STRIPE_SECRET_KEY }}/g' .env.secrets
                  sed -i 's/<whsk>/${{ secrets.STRIPE_WH_SECRET }}/g' .env.secrets

            - name: Deploy
              working-directory: ./infra/k8s/overlays/prod
              run: |-
                  kubectl apply -k .
