name: Review-ms build and push docker image

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  test:
    name: try npm packagev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: gateway-service
      - name: echo
        run: echo ${{ steps.package-version.outputs.current-version }}
