name: Test whole architecture

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
    paths:
      - "*-service/**"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start docker containers
        run: |
          docker compose -f compose.test.yml up --build --detach 
          # docker compose exec -T server npm run test
